-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for books
create table books (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  author text,
  cover_url text,
  total_pages int,
  current_page int default 0,
  status text check (status in ('toread', 'reading', 'finished')) default 'toread',
  rating int check (rating >= 0 and rating <= 5),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for books
alter table books enable row level security;

create policy "Users can view their own books."
  on books for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own books."
  on books for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own books."
  on books for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own books."
  on books for delete
  using ( auth.uid() = user_id );

-- Create a table for nuggets (takeaways)
create table nuggets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  book_id bigint references books on delete cascade,
  content text not null,
  page_number int,
  tags text[],
  is_favorite boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for nuggets
alter table nuggets enable row level security;

create policy "Users can view their own nuggets."
  on nuggets for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own nuggets."
  on nuggets for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own nuggets."
  on nuggets for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own nuggets."
  on nuggets for delete
  using ( auth.uid() = user_id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
