-- Migration: Add sharing feature support
-- Run this in Supabase SQL Editor

-- Step 1: Add metadata fields to books table
ALTER TABLE books ADD COLUMN IF NOT EXISTS publisher text;
ALTER TABLE books ADD COLUMN IF NOT EXISTS published_date text;
ALTER TABLE books ADD COLUMN IF NOT EXISTS isbn text;

-- Step 2: Add note field to nuggets table  
ALTER TABLE nuggets ADD COLUMN IF NOT EXISTS note text;

-- Step 3: Create shared_nuggets table
CREATE TABLE IF NOT EXISTS shared_nuggets (
  id bigint generated by default as identity primary key,
  nugget_id bigint references nuggets on delete cascade not null,
  share_id text unique not null,
  created_by uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  view_count int default 0
);

-- Step 4: Create index for fast lookup
CREATE INDEX IF NOT EXISTS idx_shared_nuggets_share_id ON shared_nuggets(share_id);

-- Step 5: Enable RLS
ALTER TABLE shared_nuggets ENABLE ROW LEVEL SECURITY;

-- Step 6: Create RLS policies
DROP POLICY IF EXISTS "Shared nuggets are publicly viewable" ON shared_nuggets;
CREATE POLICY "Shared nuggets are publicly viewable"
  ON shared_nuggets FOR SELECT
  USING ( true );

DROP POLICY IF EXISTS "Users can create shares for their nuggets" ON shared_nuggets;
CREATE POLICY "Users can create shares for their nuggets"
  ON shared_nuggets FOR INSERT
  WITH CHECK ( auth.uid() = created_by );

DROP POLICY IF EXISTS "Users can delete their shares" ON shared_nuggets;
CREATE POLICY "Users can delete their shares"
  ON shared_nuggets FOR DELETE
  USING ( auth.uid() = created_by );
